parcial/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Noticia;
use App\Http\Controllers\NoticiaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('noticias',NoticiaController::class);
Route::get('noticiasSoloImagen/{pag?}',[NoticiaController::class, 'mostrarNoticiasSoloImagen'])->name('solo-imagen');
Route::get('noticiasAutor/{autor}/{pag?}',[NoticiaController::class, 'porAutor'])->name('con-autor');
Route::get('noticiasCarrera/{carrera}/{pag?}',[NoticiaController::class, 'porCarrera'])->name('carrera');
Route::get('noticiasCategoria/{categoria}/{pag?}',[NoticiaController::class, 'porCategoria'])->name('categoria');
Route::get('noticiasEtiqueta/{etiqueta}/{pag?}',[NoticiaController::class, 'porEtiqueta'])->name('etiqueta');

parcial/resources/views/cargarnoticias.blade.php
@extends('main');

@section('titulo','Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-secondary  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-info"><b>Nueva Noticia</b></h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::open(['route'=>'noticias.store','files'=>true])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Título'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Contenido'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$user,null,['class'=>'form-control card-text','placeholder'=>'Seleccione un Autor'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Carrera'])}}
              </div>


              <div class="form-group">
              <em><strong>{{Form::label("Etiquetas",null,['class'=>'control-label card-text text-dark'])}}</em></strong></br>
                @foreach($etiqueta as $id=>$nombre)
                <div class="form-check form-check-inline mt-2 ml-1">
                  <span class="badge badge-info text-dark">
                     {{Form::checkbox("etiqueta".$id,$id,null,['class'=>'check-input mt-1'])}}
                     {{Form::label($id,$nombre,['class'=>'check-label '])}}
                  </span>
                </div>
                @endforeach
              </div>


              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                {{Form::file("imagen")}}
              </div>
            <div class="card-footer">
              <button class="btn btn-danger text-dark" type="submit" style="width:100%;"><strong>Guardar</strong></button>
            </div>
              
              {!!Form::close()!!}
            
        </div>
    </div>
</div>

@endsection

parcial/resources/views/crearnoticiasimagen.blade.php
@extends('main');

@section('titulo','Noticias')
@section('contenido')

@forelse($contenidoNoticias as $noticia)

@if($loop->iteration % 2!=0)
<div class="row"> 
@endif

    <div class="col col-md-6">
        <div class="card bg-secondary text-center border border-dark m-5 ">
            @if(isset($noticia->imagen))
            @if(Str::startsWith($noticia->imagen, 'http'))
              <img src="{{ $noticia->imagen }}" class="card-img-top" alt="...">
            @else
              <img src="{{ asset('./storage/'. $noticia->imagen) }}" class="card-img-top" alt="...">  
            @endif
         @else
          <h5 class="text-center text-muted"> No hay imagen disponible </h5>
          <hr>
         @endif
            <div class="card-body">
                <h2 class="card-title pb-2 text-dark"><em><b>{{$noticia->titulo}}</b></em></h2>
                    <a href="{{route('carrera',['carrera'=>$noticia->perteneceA->id])}}"><p class="card-text pb-2 text-dark"><small><b><u>{{$noticia->perteneceA->nombre}}</u></b></small></p></a>
                    
                    
            <p class="card-text pb-2 text-white">{!! $noticia->contenido !!}</p>
            <a href="{{route('con-autor',['autor'=>$noticia->creadaPor->id])}}"><p class="card-text pb-2 text-light"><small>By <i>{{$noticia->creadaPor->name}}</i></small></p></a>

            <div class="row">
            <div class="col col-md-12 text-center">
                @foreach($noticia->etiquetas as $e)
                <a href="{{route('etiqueta',['etiqueta'=>$e->id])}}"><span class="badge badge-info text-dark mr-2 mt-2">{{$e->nombre}}</span></a>
                @endforeach
            </div>
            </div>
                
            </div>
            <div class="card-footer text-center">
                <div class="row">
                    <div  class="offset-9 mt-1">
                    <a href="{{route('noticias.show',['noticia'=>$noticia->id])}}" class=" btn btn-danger"><img src="https://www.svgrepo.com/show/38604/eye.svg" 
                    width="20" height="20" alt="Mostrar" title="Mostrar"></a>
</div>
                    <div class="ml-1 mt-1">
                    <a href="{{route('noticias.edit',['noticia'=>$noticia->id])}}" class=" btn btn-danger"><img src="https://www.svgrepo.com/show/6308/pen.svg" 
                    width="20" height="20" alt="Editar" title="Editar"></a>
</div>
                    <div class="ml-1 mt-1">

                    {{Form::model($noticia,['method'=>'delete','route'=>['noticias.destroy',$noticia->id]])}}
                    @csrf
                    
                    <button type="submit" class="btn btn-danger" onclick="if (!confirm('Está seguro de borrar la noticia?')) return false;"><img src="https://www.svgrepo.com/show/80902/trash.svg" width="20" height="20" alt="Borrar" 
                    title="Borrar"></button>
                    {!!Form::close()!!}
                </div>

                </div>
            </div>

        </div>
        </div>

@if($loop->iteration % 2==0)
</div><hr>
@endif

@if($loop->last && $loop->iteration % 2!=0)
</div> <hr>
@endif

@empty 
<div class="alert alert-danger alert-dismissible" role="aler">No hay noticias para mostrar<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

@endforelse

<div class="d-flex justify-content-center">
{!! $contenidoNoticias->links() !!}
</div>

@endsection

parcial/resources/views/main.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <title>@yield('titulo')</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body class="bg-dark">

  <nav class="navbar navbar-expand-lg navbar-expand-md  bg-info text-dark ">
        <div class="container-fluid">
            <div class="navbar-header" >
                <img src="../descarga.jpg" alt="image" width="30px" class="img-thumnbnail"><b> ISFT 38</b>
            </div>
            <div class="collapse navbar-collapse ml-3">
                <ul class="navbar-nav  ">
                    <li class="nav-item"><a class="nav-link text-white" href="{{route('noticias.index')}}">Noticias</a></li>
                    <li class="nav-item"><a class="nav-link  text-white" href="{{route('solo-imagen')}}">Con Imágen</a></li>
                    <li class="nav-item"><a class="nav-link  text-white" href="{{route('noticias.create')}}">Crear Noticias</a></li>
                </ul>
            </div>
        </div>
    </nav>
<br>
<div class="container-fluid bg-dark">
        <div class="row">
            <div class="col col-md-12">
           
@yield('contenido')

</div>
</div>
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    </body>
</html>

parcial/resources/views/modificarnoticias.blade.php
@extends('main');

@section('titulo','Modificar Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-secondary  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-dark"><b>Modificar Noticia: "{{$noticia->titulo}}"</b></h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::model($noticia,['method'=>'put','route'=>['noticias.update',$noticia->id],'files'=>true])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Título'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Contenido'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$usuario,null,['class'=>'form-control card-text','placeholder'=>'Seleccione un Autor'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Carrera'])}}
              </div>


              <div class="form-group">
              <em><strong>{{Form::label("Etiquetas",null,['class'=>'control-label card-text text-dark'])}}</em></strong></br>
                @foreach($etiqueta as $id=>$nombre)
                <div class="form-check form-check-inline mt-2 ml-1">
                  <span class="badge badge-info text-dark">
                    @if($noticia->etiquetas()->find($id))
                     {{Form::checkbox("etiqueta".$id,$id,'X',['class'=>'check-input mt-1'])}}
                     {{Form::label($id,$nombre,['class'=>'check-label'])}}
                     @else
                     {{Form::checkbox("etiqueta".$id,$id,null,['class'=>'check-input mt-1'])}}
                     {{Form::label($id,$nombre,['class'=>'check-label'])}}
                     @endif
                  </span>
                </div>
                @endforeach
              </div>




              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                @if($noticia->imagen)
                    @if(Str::startsWith($noticia->imagen,'http'))
                        <img src="{{$noticia->imagen}}" class="img-responsive" alt="..." width="500">
                    @else
                        <img src="{{asset('./storage/'.$noticia->imagen)}}" class="img-responsive" width="500"  alt="...">   
                        @endif
               
                @endif 
</br></br>
                {{Form::file("imagen")}}
              </div>
            <div class="card-footer">
              <button class="btn btn-danger text-dark" type="submit" style="width:100%;"><strong>Guardar</strong></button>
            </div>
              
              {!!Form::close()!!}
            
        </div>
    </div>
</div>

@endsection

parcial/resources/views/mostrar1noticia.blade.php
@extends('main');

@section('titulo','Modificar Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-secondary  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-dark"><b>Modificar Noticia: "{{$noticia->titulo}}"</b></h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::model($noticia,['method'=>'get','route'=>['noticias.show',$noticia->id]])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','readonly'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','readonly'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$usuario,null,['class'=>'form-control card-text','disabled','readonly'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','disabled','readonly'])}}
              </div>

              <div class="form-group">
              <em><strong>{{Form::label("Etiquetas",null,['class'=>'control-label card-text text-dark'])}}</em></strong></br>
                @foreach($etiqueta as $id=>$nombre)
                <div class="form-check form-check-inline mt-2 ml-1">
                  <span class="badge badge-info text-dark">
                    @if($noticia->etiquetas()->find($id))
                     {{Form::checkbox("etiqueta".$id,$id,'X',['class'=>'check-input mt-1'])}}
                     {{Form::label($id,$nombre,['class'=>'check-label'])}}
                     @endif
                  </span>
                </div>
                @endforeach
              </div>


              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                @if($noticia->imagen)
                    @if(Str::startsWith($noticia->imagen,'http'))
                        <img src="{{$noticia->imagen}}" class="img-responsive" width="500" alt="...">
                    @else
                        <img src="{{asset('./storage/'.$noticia->imagen)}}"  width="500" class="img-responsive" alt="...">   
                        @endif
                @else
                    <h5 class="text-center text-muted">No hay imagen para mostrar</h5><hr>
                @endif    
              </div>
              {!!Form::close()!!}

              <div class="card-footer">
              <button class="btn btn-danger " type="submit" style="width:100%;"><strong><a href="{{route('noticias.index')}}" class="text-white">Volver</a></strong></button>
            </div>
              
            
        </div>
    </div>
</div>

@endsection